### ISSUE TITLE
Incorrect addresses for non Latin countries

### ISSUE THREAD

**Issue by PedroDiogo** [DASPRiD/localized-address-format#16]
Hi 👋 

I’ve been using this library on a side project and it speeds things up considerably, thanks!

I found out that even though most of my addresses are formatted correctly I found an issue with an address from Hong Kong. 

Upon further investigation and confirming my inputs were correct, I was able to narrow down the issue to when I use Hong Kong as a country. 

Continuing my investigation I noticed this library uses `fmt` as opposed to `lfmt` - Stands for Latin format - on addresses formats. 

I see a couple options that can potentially fix this issue:
* Simpler - use `lfmt` instead of `fmt`. Assumes this library is always used by Latin script languages. 
* Correct - Allow both options, switched by a flag on `formatAddress`. The flag could be either default `fmt` (to maintain backwards compatibility) or `lfmt` as most languages probably use Latin script anyway. 

What do you think?

Thanks!

**Comment by DASPRiD** [comment]
Hi there, thanks for finding and investigating the issue. I agree that we should have a switch which forces the use of the Latin format if available. Looking through the original dataset, `lfmt` is only set for countries where the standard `fmt` is not Latin.

So yes, I agree with your correct solution.  I'll create an update to this ASAP.
