### ISSUE TITLE
Street number and Street

### ISSUE THREAD

**Issue by webtimo-de** [DASPRiD/localized-address-format#18]
Hello everyone; 

I have a question. Could you possibly enter that, you could also specify the street number separately in addition to the street? I personally live in Germany, and here the streets and street numbers look different than in the USA.

An example:
Germany:
John Doe
Beispiel GmbH
Musterstraße **123**
12345 Musterstadt
Deutschland

USA:
John Doe
Netflix - Headquarters
**5808** W Sunset Blvd
Los Angeles, CA 90028
United States

Thanks already in advance!

**Comment by DASPRiD** [comment]
Sadly not, the address formatting data do not separate the address lines into more detailed fields.
